# Chrome自动化登录爆破配置文件
browser:
  headless: true     # 是否无头模式
  timeout: 60        # 页面加载超时时间(秒)
  width: 1920        # 浏览器窗口宽度
  height: 1080       # 浏览器窗口高度
  chrome_path: ""    # Chrome浏览器可执行文件路径（可选，空字符串表示自动检测）

# 登录页面识别规则
login_page_detection:
  # 页面标题正则表达式
  title_patterns:
    - "(?i).*login.*"
    - "(?i).*登录.*"
    - "(?i).*sign.*in.*"
    - "(?i).*log.*in.*"
    - "(?i).*用户登录.*"
    - "(?i).*管理员登录.*"
  
  # 页面URL正则表达式
  url_patterns:
    - "(?i).*login.*"
    - "(?i).*signin.*"
    - "(?i).*auth.*"
    - "(?i).*admin.*"
    - "(?i).*user.*"
  
  # 页面内容关键词
  content_keywords:
    - "用户名"
    - "密码"
    - "登录"
    - "username"
    - "password"
    - "login"
    - "sign in"
    - "log in"
    - "账号"
    - "账户"
    - "手机号"
    - "邮箱"
    - "验证码"
    - "登录名"

  # 页面标题关键词
  title_keywords:
    - "登录"
    - "login"
    - "sign in"
    - "log in"
    - "管理系统"
    - "后台"
    - "admin"
    - "administration"
    - "auth"
    - "authentication"
    - "办公自动化"

# 表单元素识别规则
form_elements:
  # 用户名输入框识别规则
  username_selectors:
    - 'input[type="text"][name*="user"]'
    - 'input[type="text"][name*="login"]'
    - 'input[type="text"][name*="account"]'
    - 'input[type="text"][placeholder*="用户名"]'
    - 'input[type="text"][placeholder*="username"]'
    - 'input[type="text"][placeholder*="账号"]'
    - 'input[type="email"]'
    - 'input[id*="user"]'
    - 'input[id*="login"]'
    - 'input[id*="account"]'
    - 'input[class*="user"]'
    - 'input[class*="login"]'
    # 新增规则支持更多格式
    - 'input[type="text"]:not([type="password"]):not([placeholder*="验证码"]):not([placeholder*="captcha"])'
    - 'input[name*="name"]'
    - 'input[name*="mobile"]'
    - 'input[name*="phone"]'
    - 'input[placeholder*="手机号"]'
    - 'input[placeholder*="邮箱"]'
    - 'input[placeholder*="登录名"]'
    - 'input[placeholder*="账户"]'
    - 'input[id*="username"]'
    - 'input[id*="email"]'
    - 'input[id*="mobile"]'
    - 'input[class*="username"]'
    - 'input[class*="email"]'
    - 'input[class*="account"]'
    # 通用文本输入框（作为最后备选）
    - 'form input[type="text"]:first-of-type'
    - 'input[type="text"]:not([placeholder*="验证"])'
  
  # 密码输入框识别规则
  password_selectors:
    - 'input[type="password"]'
    - 'input[name*="pass"]'
    - 'input[name*="pwd"]'
    - 'input[name*="password"]'
    - 'input[placeholder*="密码"]'
    - 'input[placeholder*="password"]'
    - 'input[placeholder*="登录密码"]'
    - 'input[placeholder*="请输入密码"]'
    - 'input[placeholder*="请输入登录密码"]'
    - 'input[id*="pass"]'
    - 'input[id*="pwd"]'
    - 'input[id*="password"]'
    - 'input[class*="pass"]'
    - 'input[class*="pwd"]'
    - 'input[class*="password"]'
    - 'input[autocomplete="current-password"]'
    - 'input[autocomplete="new-password"]'
    # 更具体的选择器
    - 'input[type="password"][placeholder]'
    - 'form input[type="password"]'
    # 通用密码框（作为备选）
    - 'form input[type="password"]:first-of-type'
    - 'input[type="password"]:not([style*="display: none"]):not([style*="display:none"])'
  
  # 验证码输入框识别规则
  captcha_selectors:
    - 'input[name*="captcha"]'
    - 'input[name*="verify"]'
    - 'input[name*="code"]'
    - 'input[placeholder*="验证码"]'
    - 'input[placeholder*="captcha"]'
    - 'input[placeholder*="验证"]'
    - 'input[id*="captcha"]'
    - 'input[id*="verify"]'
    - 'input[id*="code"]'
    - 'input[class*="captcha"]'
    - 'input[class*="verify"]'
  
  # 登录按钮识别规则
  submit_selectors:
    - 'input[type="submit"]'
    - 'button[type="submit"]'
    - 'button:contains("登录")'
    - 'button:contains("Login")'
    - 'button:contains("Sign In")'
    - 'input[value*="登录"]'
    - 'input[value*="Login"]'
    - 'a[class*="login"]'
    - 'div[class*="login-btn"]'
    - 'span:contains("登录")'

  # 复选框识别规则（如用户协议、服务条款等）
  checkbox_selectors:
    - 'input[type="checkbox"]'
    - 'input[name*="agree"]'
    - 'input[name*="accept"]'
    - 'input[name*="terms"]'
    - 'input[name*="policy"]'
    - 'input[name*="protocol"]'
    - 'input[id*="agree"]'
    - 'input[id*="accept"]'
    - 'input[id*="terms"]'
    - 'input[id*="policy"]'
    - 'input[class*="agree"]'
    - 'input[class*="accept"]'
    - 'input[class*="terms"]'
    - 'input[class*="checkbox"]'

# 爆破配置
bruteforce:
  # 用户名字典
  usernames:
    - "admin"
    - "administrator"
    - "root"
    - "user"
    - "test"
    - "guest"
    - "demo"
    - "管理员"
  
  # 密码字典
  passwords:
    - "admin"
    - "password"
    - "123456"
    - "admin123"
    - "root"
    - "test"
    - "guest"
    - "demo"
    - "123456789"
    - "qwerty"
    - "password123"
    - "admin@123"
  
  # 爆破间隔时间(秒)
  delay: 2
  
  # 最大重试次数
  max_retries: 3
  
  # 并发数
  concurrent: 1

# 日志配置
logging:
  level: "error"  # debug, info, warn, error
  file: ""  # 空字符串表示输出到控制台
  format: "text"  # text, json
  
  # 日志文件管理
  file_management:
    # 是否保存到文件
    save_to_file: true
    
    # 日志文件目录
    log_dir: "logs"
    
    # 日志文件名格式 (支持时间格式化)
    filename_format: "2006-01-02.log"
    
    # 保留日志文件数量 (0表示全部保留)
    max_files: 0
    
    # 单个日志文件最大大小 (MB)
    max_size: 100
    
    # 是否按日期轮转
    rotate_by_date: true

# 结果存储配置
results:
  # 结果保存目录
  save_dir: "result"
  
  # 成功结果文件名格式
  success_filename_format: "2006-01-02_success.txt"
  
  # 失败结果文件名格式 (可选，空表示不保存失败结果)
  failure_filename_format: ""
  
  # 结果格式: url:username:password
  format: "url:username:password"
  
  # 是否实时保存结果
  realtime_save: true

# 验证码处理配置
captcha:
  # 验证码检测配置
  detection:
    enabled: true                    # 是否启用验证码检测
    timeout: 10                      # 检测超时时间(秒)
    confidence_threshold: 0.7        # 检测置信度阈值
    verbose_output: true             # 是否输出详细的验证码检测信息
    
  # 验证码处理策略
  handling:
    skip_on_detection: true          # 检测到验证码时是否跳过
    manual_input: false              # 是否支持人工输入
    ocr_enabled: false               # 是否启用OCR识别
    
  # OCR配置
  ocr:
    # 主要OCR提供商配置
    primary_provider: "tesseract"    # 主要OCR提供商: tesseract, baidu, aliyun, tencent, local
    
    # 备用OCR提供商（主要提供商失败时使用）
    fallback_providers: 
      - "local"
      - "tesseract"
    
    # 通用OCR配置
    timeout: 30                      # OCR识别超时(秒)
    max_retries: 3                   # 最大重试次数
    retry_delay: 2                   # 重试间隔(秒)
    
    # 图像预处理配置
    preprocessing:
      enabled: true                  # 是否启用图像预处理
      resize_enabled: true           # 是否调整图像大小
      resize_width: 200              # 调整后的宽度(像素)
      resize_height: 80              # 调整后的高度(像素)
      grayscale: true                # 是否转为灰度图
      noise_reduction: true          # 是否降噪
      contrast_enhancement: true     # 是否增强对比度
      binary_threshold: 128          # 二值化阈值(0-255)
      
    # Tesseract配置
    tesseract:
      executable_path: ""            # Tesseract可执行文件路径(空为自动检测)
      language: "eng+chi_sim"        # 识别语言: eng(英文), chi_sim(简体中文), chi_tra(繁体中文)
      page_seg_mode: 8               # 页面分割模式: 6(单一文本块), 7(单行文本), 8(单词), 13(原始行)
      char_whitelist: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"  # 字符白名单
      
    # 百度OCR配置
    baidu:
      app_id: ""                     # 百度AI开放平台APP ID
      api_key: ""                    # 百度AI开放平台API Key  
      secret_key: ""                 # 百度AI开放平台Secret Key
      api_url: "https://aip.baidubce.com/rest/2.0/ocr/v1/accurate_basic"  # API地址
      
    # 阿里云OCR配置
    aliyun:
      access_key_id: ""              # 阿里云Access Key ID
      access_key_secret: ""          # 阿里云Access Key Secret
      region: "cn-hangzhou"          # 地域
      endpoint: "ocr.cn-hangzhou.aliyuncs.com"  # 服务端点
      
    # 腾讯云OCR配置
    tencent:
      secret_id: ""                  # 腾讯云Secret ID
      secret_key: ""                 # 腾讯云Secret Key
      region: "ap-beijing"           # 地域
      endpoint: "ocr.tencentcloudapi.com"  # 服务端点
      
    # 本地机器学习模型配置
    local:
      model_path: "models/captcha_model.h5"  # 模型文件路径
      enabled: false                 # 是否启用本地模型
      confidence_threshold: 0.8      # 置信度阈值
      
  # 滑块验证码配置
  slider:
    enabled: true                    # 是否启用滑块处理
    simulate_human: true             # 是否模拟人类行为
    drag_speed: 100                  # 拖拽速度(像素/秒)
    random_delay: true               # 是否随机延迟
    min_delay: 500                   # 最小延迟(毫秒)
    max_delay: 2000                  # 最大延迟(毫秒)
    
  # 点击验证码配置
  click:
    enabled: true                    # 是否启用点击验证码处理
    click_delay: 500                 # 点击间隔(毫秒)
    max_attempts: 3                  # 最大尝试次数
    
  # 自定义验证码选择器
  custom_selectors:
    # 验证码图片选择器
    image_selectors:
      - "img[src*='captcha']"
      - "img[src*='verify']"
      - "img[src*='vcode']"
      - "img[alt*='验证码']"
      - "img[alt*='captcha']"
      - ".captcha-img"
      - ".verify-img"
      - "#captcha_img"
      - "#verify_img"
    
    # 验证码输入框选择器  
    input_selectors:
      - "input[placeholder*='验证码']"
      - "input[name*='captcha']"
      - "input[name*='verify']"
      - "input[name*='code']"
      - "#captcha_code"
      - "#verify_code"
      - ".captcha-input"
    
    # 滑块选择器
    slider_selectors:
      - ".slider-captcha"
      - ".slide-captcha"
      - ".geetest_slider"
      - ".nc_iconfont"
      - ".yidun_slider"
      - "[class*='slider'][class*='verify']" 